apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-nextflow
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name:  pv-nextflow