apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: custom-claim-nextflow
spec:
  storageClassName: nextflow-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name:  pv-nextflow