apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nextflow
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  hostPath:
    path: ////D/WorkSpace/fullstack/virus/nextflow